### ISSUE TITLE
fatal: [CentOS]: FAILED! => {"changed": false, "msg": "Could not find the requested service mosquitto: "}

### ISSUE THREAD

**Issue by onksingh** [samdoran/ansible-role-mosquitto#1]
i am getting this error while running molecule test.

**Comment by samdoran** [comment]
Which version of CentOS are you using?

**Comment by onksingh** [comment]
centos7

**Comment by samdoran** [comment]
I'm unable to duplicate this. The tests are passing [in CI](https://travis-ci.org/samdoran/ansible-role-mosquitto/jobs/476422422) as well as locally for me. 

Could you provide the output for `molecule test`?

My best guess is the `mosquitto` package is not being installed and therefore the unit file is not present.

**Comment by onksingh** [comment]
Actually, I am using centos:7 images and haven't mounted the volume and passed the command to get the output, might be the reason of not getting the service result.
but when I used the same image you have used, it started working.
