### ISSUE TITLE
Most naive container setup fails

### ISSUE THREAD

**Issue by nickdavies** [samdoran/ansible-role-mosquitto#3]
I started by just setting the method with:
```
mqtt_installation_method: container
```

and this gave me an error that said that networking type `host` is incompatible with exporting ports:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
fatal: [hass-pi]: FAILED! => {"changed": false, "msg": "An unexpected docker error occurred: \"host\" network_mode is incompatible with port_bindings"}
```

I then set either `mqtt_container_network_mode` to `bridge` or make published ports empty. So the config I had became:

```
mqtt_installation_method: container
mqtt_container_published_ports:
```

Now ancible completes successfully but looking at the logs for the container and it can't modify the pid file:
```
1618810841: The 'port' option is now deprecated and will be removed in a future version. Please use 'listener' instead.
1618810841: Error: Unable to write pid file.
1618810841: The 'port' option is now deprecated and will be removed in a future version. Please use 'listener' instead.
1618810841: Error: Unable to write pid file.
....
```

In the config template there is an option to not set this field:
```
{% if mqtt_pid_file is defined %}
pid_file {{ mqtt_pid_file }}
{% endif %}
```

but because it's in defaults I couldn't figure out how to do that.

Doing this fixes the issue but could be annoying for non-container users or people who want the pid for whatever reason
```
diff --git a/defaults/main.yml b/defaults/main.yml
index fdbbb43..687e587 100644
--- a/defaults/main.yml
+++ b/defaults/main.yml
@@ -8,7 +8,6 @@ mqtt_config_files:
     mode: '0600'
 
 mqtt_accounts: []
-mqtt_pid_file: /var/run/mosquitto.pid
 mqtt_user: mosquitto
 mqtt_group: mosquitto
 mqtt_port: 1883
```

I ended up with a work around without touching the code by setting the pid file to something that can be written that was already mounted in eg I did:

```
mqtt_installation_method: container
mqtt_container_published_ports:
mqtt_pid_file: "/mosquitto/data/mosquitto.pid"
```

Not sure what your thoughts on the best solution here is. Perhaps just an example setup for the container module would be enough.

**Comment by samdoran** [comment]
Sorry for the headaches. There's some room for refinement here.

I think removing the `mqtt_pid_file` setting is the best solution since it's optional. ~You could set `mqtt_pid_file: ~` to override the default value to `None` which would prevent it from being put in the final config.~ (that doesn't work how I thought because the check is `is defined` not "truthy").

Regarding the networking mode and published ports, I'm not sure why I set the default to `host`. I think that should be changed to `bridge` and then published ports would work as expected.
