### ISSUE TITLE
Native AlmaLinux requires epel-release to install mosquitto

### ISSUE THREAD

**Issue by jmidgren** [samdoran/ansible-role-mosquitto#6]
I used this role to install Mosquitto on AlmaLinux 8 running in an LXD container. My playbook failed on the step `samdoran.mosquitto : RHEL | Install packages` with the message `"No package mosquitto available."`

Checking this manually, I came to the conclusion that adding EPEL manually (`dnf install -y epel-release`) before running the playbook again, solved the issue. Unfortunately though, installing EPEL seems to be done [in a different fashion depending on what distribution you are on](https://docs.fedoraproject.org/en-US/epel/). Thus, a simple solution to this problem is perhaps to note in the documentation that native installation on "Enterprise Linux" requires EPEL. For Ansible Galaxy you may refer to e.g. the collection [gotmax23.epel](https://galaxy.ansible.com/gotmax23/epel), which handles this (I tested it for my setup).

By the way, with EPEL out of the way I found that the role worked fine also on AlmaLinux 9, although not mentioned on Ansible Galaxy.

Thanks for the role! :pray:

**Comment by samdoran** [comment]
That makes sense. I will update the docs to list that as a prerequisite.

I haven't done much with AlmaLinux. I have a [role that installs EPEL](https://galaxy.ansible.com/samdoran/repo_epel). I'll update it to work with AlmaLinux.

**Comment by samdoran** [comment]
I've updated the documentation and my EPEL role.

**Comment by jmidgren** [comment]
Excellent! :+1:
